task:
    alias: pkg
    freebsd_instance:
      cpu: 4
      memory: 16G
      matrix:
        - image: freebsd-13-1-release-amd64
        # image: freebsd-14-0-current-amd64-v20220701

    env:
      CIRRUS_CLONE_DEPTH: 1
      GITHUB_TOKEN: ENCRYPTED[53a7e28d3a96e84dcfc38da4df73c32521b000794598caa1de582dda1afee5fab653d43f80d86f7fd1713f81581eee38]
      BATCH: 1

    timeout_in: 90m

    prerequisites_script:
      - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
      - pkg install -y git-lite
      # Only download ports infrastructure but no ports; https://stackoverflow.com/a/52269934/2988
      # rm -rf /usr/ports
      # git clone --depth 1 --filter=blob:none --sparse https://github.com/freebsd/freebsd-ports.git /usr/ports
      # ( cd /usr/ports ; git sparse-checkout set Keywords Mk Templates Tools ; cd - )
      
    build_script:
      - ./build.sh
      
    binary_artifacts:
      path: "FreeBSD:**/*"
