task:
    freebsd_instance:
      cpu: 4
      memory: 16G
      matrix:
        - image: freebsd-13-1-release-amd64
        - image: freebsd-14-0-current-amd64-v20220701
        
    env:
      CIRRUS_CLONE_DEPTH: 1
      GITHUB_TOKEN: ENCRYPTED[02e03fdb075b334413c7bf1d38bce7f31ff19319bd163e0a3509a8ebe90dea8f3339571a87c69b8355d3bb8d796a632a]
      BATCH: 1 

    timeout_in: 90m
    
    prerequisites_script:
      - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
      - pkg install -y git-lite
      # Only download ports infrastructure but not other ports; https://stackoverflow.com/a/52269934/2988
      - rm -rf /usr/ports
      - git clone --depth 1 --filter=blob:none --sparse https://github.com/freebsd/freebsd-ports.git /usr/ports
      - ( cd /usr/ports ; git sparse-checkout set Keywords Mk Templates Tools ; cd - )
      
    install_dependencies_script:
      - ( cd sysutils/hellodesktop-launch && make build-depends-list | cut -c 12- | xargs pkg install -y ) 
      - ( cd x11-wm/hellodesktop-menu && make build-depends-list | cut -c 12- | xargs pkg install -y )
      - ( cd x11-fm/hellodesktop-filer && make build-depends-list | cut -c 12- | xargs pkg install -y )
      
    build_package_script:
      - mkdir -p ./pkg/
      - make -C sysutils/hellodesktop-launch package
      - make -C x11-wm/hellodesktop-menu package
      - make -C x11-fm/hellodesktop-filer package
      - find . -name '*.pkg' -exec mv {} ./pkg \;
      
    binary_artifacts:
      path: "pkg/*"
  
